#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
https://leetcode.com/problems/find-the-difference/description/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one
more letter at a random position.

t = rnd(s) + char in random position.

Find the letter that was added in t.

用 set?

Example:
Input:
s = "a"
t = "aa"

Output:
a

Explanation:
'e' is the letter that was added.
"""


class Solution(object):

    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        sdict = {}

        for c in s:
            if c in sdict:
                sdict[c] += 1
            else:
                sdict[c] = 1

        for c in t:
            if c not in sdict:
                return c
            else:
                sdict[c] -= 1
                if sdict[c] == -1:
                    return c


def build_input():
    s = "a"
    t = "aa"
    return s, t


if __name__ == "__main__":
    s, t = build_input()
    r = Solution()
    result = r.findTheDifference(s, t)
    print(result)
